In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
from scipy import integrate

# Лабораторная работа №2. Решение систем линейных уравнений

# Создание матрицы. Работа с элементами матрицы

1. Создать матрицу 10x10 случайных целых чисел принадлежащих отрезку [0, 10]. 

In [2]:
A = np.random.randint(0,11,(10, 10))
print(A)

[[ 5  3 10  5  0  8  4  2  9  3]
 [ 9  0  7 10  3  2  7  7  0  8]
 [ 4  7  8  0  7  0  0  2  6  5]
 [ 7  7  2 10  2  5  5  7  1  6]
 [ 0  0  4  7  8  9  3  8 10  6]
 [ 9  2 10  0  1  0  4 10  3  5]
 [ 3  1  4  8  1  2  3  5  8  0]
 [10  6  9  4  7  0  4  2  8  6]
 [ 7  7  8  6  1  4  4  8  9  2]
 [ 8  1  1  4  6  4  9  2  4  9]]


Обращение к элементу матрицы, стоящему в 4 строке,  3 столбце

In [3]:

A[4,3]

7

Четвертый (!) столбец матрицы А:

In [4]:
A[:, 3]

array([ 5, 10,  0, 10,  7,  0,  8,  4,  6,  4])

Седьмая (!) строка матрицы А:

In [5]:
A[6, :]

array([3, 1, 4, 8, 1, 2, 3, 5, 8, 0])

Вся матрица:

In [6]:
A[:,:]

array([[ 5,  3, 10,  5,  0,  8,  4,  2,  9,  3],
       [ 9,  0,  7, 10,  3,  2,  7,  7,  0,  8],
       [ 4,  7,  8,  0,  7,  0,  0,  2,  6,  5],
       [ 7,  7,  2, 10,  2,  5,  5,  7,  1,  6],
       [ 0,  0,  4,  7,  8,  9,  3,  8, 10,  6],
       [ 9,  2, 10,  0,  1,  0,  4, 10,  3,  5],
       [ 3,  1,  4,  8,  1,  2,  3,  5,  8,  0],
       [10,  6,  9,  4,  7,  0,  4,  2,  8,  6],
       [ 7,  7,  8,  6,  1,  4,  4,  8,  9,  2],
       [ 8,  1,  1,  4,  6,  4,  9,  2,  4,  9]])

Минор второго порядка на пересечении 2-3 строки и 4-5 столбцов

In [7]:
A[1:3, 3:5]

array([[10,  3],
       [ 0,  7]])

# Умножение матриц

Скалярный вид умножения матриц.

In [8]:
n = 3
k = 4
m = 5
A =  np.random.randint(0,11,(n, k))
B = np.random.randint(0,11,(k, m))
C = np.zeros((n,m), dtype = int)

In [9]:
for i in range(n):
    for j in range(m):
        for p in range(k):
            C[i,j] = C[i,j] + A[i,p]*B[p,j]

In [10]:
D = np.dot(A, B)
print('C=\n', C)
print('A*B=\n', D)

C=
 [[206 204 233 201 184]
 [158 162 240 224 187]
 [120 106 152 120 138]]
A*B=
 [[206 204 233 201 184]
 [158 162 240 224 187]
 [120 106 152 120 138]]


In [11]:
#векторное умножение матриц
for i in range(n):
    for j in range(m):
            C[i,j] = np.dot(A[i, :], B[:, j])

In [12]:
print(C)

[[206 204 233 201 184]
 [158 162 240 224 187]
 [120 106 152 120 138]]


# Решение системы линейных уравнений с треугольной матрицей А

In [13]:

A = np.array([[1, 0, 0], [3, 1, 0], [-4, 5, 1]], int) # Матрица (левая часть системы)
B = np.array([2, 4, 3], int) # Вектор (правая часть системы)
x = np.zeros((3,1), int)

x[0] = B[0]

for i in range(1,3):
    x[i] = B[i] - np.dot(A[i, :i], x[ :i])
                         
                         
print(x)
print(A)
B


[[ 2]
 [-2]
 [21]]
[[ 1  0  0]
 [ 3  1  0]
 [-4  5  1]]


array([2, 4, 3])

In [22]:
#проверим решение
np.linalg.solve(A, B)

array([ 2., -2., 21.])

In [27]:
# решение без дополнительной переменной

A = np.array([[1, 0, 0], [3, 1, 0], [-4, 5, 1]], int) # Матрица (левая часть системы)
B = np.array([2, 4, 3], int) # Вектор (правая часть системы)


for i in range(1,3):
    B[i] = B[i] - np.dot(A[i, :i], B[ :i])
                         
                         
print(B)

[ 2 -2 21]


# LU разложение матрицы А

In [144]:
n = 4
A =  np.random.randint(1,11, (n,n))
A1 = A.copy() #контрольная матрица
print(A)

[[ 1  6  4  5]
 [ 5  2  9 10]
 [10  3 10  8]
 [ 6  4  3  6]]


In [145]:
print(A)

[[ 1  6  4  5]
 [ 5  2  9 10]
 [10  3 10  8]
 [ 6  4  3  6]]


In [146]:
#алгоритм с вики
U = np.zeros((n,n), float)
L = np.identity(n, float)

for i in range(n):
    for j in range(n):
        if i<=j:
            U[i,j] = A1[i,j] -  np.dot(L[i, :i], U[ :i, j])
        if i>j:
            L[i,j] = (A1[i,j] -  np.dot(L[i, :j], U[ :j, j]) )/ U[j,j]

In [147]:
print(L)
print(U)
print(np.dot(L,U))
print(np.dot(L,U) == A1)

[[ 1.          0.          0.          0.        ]
 [ 5.          1.          0.          0.        ]
 [10.          2.03571429  1.          0.        ]
 [ 6.          1.14285714  1.10798122  1.        ]]
[[  1.           6.           4.           5.        ]
 [  0.         -28.         -11.         -15.        ]
 [  0.           0.          -7.60714286 -11.46428571]
 [  0.           0.           0.           5.84507042]]
[[ 1.  6.  4.  5.]
 [ 5.  2.  9. 10.]
 [10.  3. 10.  8.]
 [ 6.  4.  3.  6.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [140]:
#не РАБОТАЕТ!!!
for k in range(n-1):
    A[k+1: , k] = A[k+1: , k] / A[k,k]
  
    A[k+1: , k+1: ] = A[k+1: , k+1: ] - np.dot(A[k+1 : , k], A[k, k+1 : ])



In [142]:
#найдем матрицы L и U:
L = np.zeros((n,n), float)
for i in range(1, n):
    for j in range(i):
        L[i,j] = A[i,j]
        
U = A - L
for i in range(n):
    L[i,i] = 1
print('U=\n', U)
print('L=\n', L)

U=
 [[  2.64730045  10.34828577   5.00494619  10.60342456]
 [  0.         -72.65603906 -76.27324636 -72.58768322]
 [  0.           0.          76.46579162  84.26810036]
 [  0.           0.           0.          -3.99405665]]
L=
 [[1.         0.         0.         0.        ]
 [3.32736463 1.         0.         0.        ]
 [1.30946765 1.01193209 1.         0.        ]
 [3.89580853 1.08997114 1.00217754 1.        ]]


In [143]:
print(np.dot(L,U) == A1)

[[ True  True  True  True]
 [ True False False False]
 [ True False False False]
 [ True False False False]]
